// TODO use size_t instead of u in V3u?

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>

int main(int argc, char** argv) {

	FILE* in_obj = fopen(argv[1], "r");

	char asset_name[] = "cube.h";
	FILE* out_h  = fopen(asset_name, "w");

	size_t vertex_count = 0;
	size_t face_count = 0;
	char* line;
	size_t len;
	// first pass, count vertices and faces
	while (getline(&line, &len, in_obj) != -1) {

		switch (line[0]) {
		case 'v':
			if (line[1] != ' ') break;
			vertex_count += 1;
			break;
		case 'f':
			if (line[1] != ' ') break;
			face_count +=1;
			break;
		default:
			break;
		}
	}

	strtok(asset_name, ".");
	asset_name[0] = toupper(asset_name[0]);

	fprintf(out_h, "/* This asset was automatically generated by objToC. */\n");
	fprintf(out_h, "typedef struct {\n");
	fprintf(out_h, "	V3f v[%zu];\n", vertex_count);
	fprintf(out_h, "	V3u f[%zu];\n", face_count);
	fprintf(out_h, "} %s;\n\n", asset_name);

	fprintf(out_h, "static const %s ", asset_name);
	asset_name[0] = tolower(asset_name[0]);
	fprintf(out_h, "%s = {\n", asset_name);

	rewind(in_obj);
	size_t count = 0;
	while (getline(&line, &len, in_obj) != -1) {

		switch (line[0]) {
		case 'v':
			// only vertices for now
			if (line[1] != ' ') break;
			if (count == 0) fprintf(out_h, "\t.v = {\n");

			char* tokv0 = strtok(line, "\040\n\t");
			char* tokv1 = strtok(NULL, "\040\n\t");
			char* tokv2 = strtok(NULL, "\040\n\t");
			char* tokv3 = strtok(NULL, "\040\n\t");

			if (count < vertex_count-1) {
				fprintf(out_h, "\t\t{ %s, %s, %s},\n", tokv1, tokv2, tokv3);
				count += 1;
			} else {
				fprintf(out_h, "\t\t{ %s, %s, %s}\n", tokv1, tokv2, tokv3);
				fprintf(out_h, "\t};\n");
				count = 0;
			}

			break;

		case 'f':
			if (line[1] != ' ') break;
			if (count == 0) fprintf(out_h, "\t.f = {\n");

				char* tok0 = strtok(line, "\040\n\t");
				char* tok1 = strtok(NULL, "\040\n\t");
				char* tok2 = strtok(NULL, "\040\n\t");
				char* tok3 = strtok(NULL, "\040\n\t");

				if (strchr(tok1, '/')) {
					tok1 = strtok(tok1, "/");
					tok2 = strtok(tok2, "/");
					tok3 = strtok(tok3, "/");
				}

			if (count < face_count-1) {
				fprintf(out_h, "\t\t{ %s, %s, %s},\n", tok1, tok2, tok3);
				count += 1;
			} else {
				fprintf(out_h, "\t\t{ %s, %s, %s}\n", tok1, tok2, tok3);
				fprintf(out_h, "\t};\n");
				count = 0;
			}
			break;
		default:
			break;
		}
	}
	fprintf(out_h, "};");
	free(line);

	fclose(in_obj);
	fclose(out_h);
	return 0;
}

